<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-3M09JOB" failures="0" tests="3" name="executePageClasses.ExecuteLoginPageClass" time="29.708" errors="1" timestamp="2023-06-20T20:37:59 IST" skipped="0">
  <testcase classname="executePageClasses.ExecuteLoginPageClass" name="verifyTheCurrentPageIsOpenWhileHittingTheUrl" time="14.830"/>
  <system-out/>
  <testcase classname="executePageClasses.ExecuteLoginPageClass" name="verifyUnSuccessfullLogin" time="12.643">
    <error message="
Found two providers called &#039;DataProvider1&#039; on class executePageClasses.DataProviderLogin" type="org.testng.TestNGException">
      <![CDATA[org.testng.TestNGException: 
Found two providers called 'DataProvider1' on class executePageClasses.DataProviderLogin
at org.testng.internal.Parameters.findDataProvider(Parameters.java:641)
at org.testng.internal.Parameters.findDataProvider(Parameters.java:510)
at org.testng.internal.Parameters.handleParameters(Parameters.java:763)
at org.testng.internal.Parameters.handleParameters(Parameters.java:728)
at org.testng.internal.invokers.ParameterHandler.handleParameters(ParameterHandler.java:72)
at org.testng.internal.invokers.ParameterHandler.createParameters(ParameterHandler.java:51)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:924)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- verifyUnSuccessfullLogin -->
  <system-out/>
  <testcase classname="executePageClasses.ExecuteLoginPageClass" name="verifySuccessfullLogin" time="2.235"/>
  <system-out/>
</testsuite> <!-- executePageClasses.ExecuteLoginPageClass -->
